export const ROUTE_PATHS = {
  ROOT: '/',
  INSTALL: '/install',
  INSTALL_DETAIL: '/install/:method',
  INSTANCES: '/instances',
  INSTANCE_DETAIL: '/instances/:id',
  DEVICES: '/devices',
  CLAW_CENTER: '/claw-center',
  CLAW_DETAIL: '/claw-center/:id',
  MARKET: '/market',
  SKILL_DETAIL: '/market/:id',
  SKILL_PACK_DETAIL: '/market/packs/:id',
  APPS: '/apps',
  APP_DETAIL: '/apps/:id',
  COMMUNITY: '/community',
  COMMUNITY_NEW: '/community/new',
  COMMUNITY_DETAIL: '/community/:id',
  GITHUB: '/github',
  GITHUB_DETAIL: '/github/:id',
  HUGGINGFACE: '/huggingface',
  HUGGINGFACE_DETAIL: '/huggingface/:id',
  CHANNELS: '/channels',
  TASKS: '/tasks',
  CHAT: '/chat',
  SETTINGS: '/settings',
  DOCS: '/docs',
} as const;
