packages:
  - 'packages/sdkwork-claw-*'
  - '../openchat/sdkwork-im-sdk/sdkwork-im-sdk-typescript/composed'
  - '../openchat/sdkwork-im-sdk/sdkwork-im-sdk-typescript/adapter-wukongim'
  - '../openchat/sdkwork-im-sdk/sdkwork-im-sdk-typescript/generated/server-openapi'
  - '../sdkwork-core/sdkwork-core-pc-react'
  - '../../spring-ai-plus-app-api/sdkwork-sdk-app/sdkwork-app-sdk-typescript'
  - '../../sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript'

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
