export { createDesktopApp } from './desktop/bootstrap/createDesktopApp';
export { DESKTOP_COMMANDS, DESKTOP_EVENTS } from './desktop/catalog';
export {
  DesktopBridgeError,
  getDesktopWindow,
  invokeDesktopCommand,
  isTauriRuntime,
  listenDesktopEvent,
  runDesktopOrFallback,
} from './desktop/runtime';
export {
  captureScreenshot,
  closeWindow,
  configureDesktopPlatformBridge,
  copyPath,
  createDirectory,
  desktopTemplateApi,
  fetchRemoteUrl,
  getApiRouterAdminBootstrapSession,
  installApiRouterClientSetup,
  getApiRouterRuntimeStatus,
  getAppConfig,
  getAppInfo,
  getAppPaths,
  setAppLanguage,
  getDesktopKernelInfo,
  getDesktopStorageInfo,
  getDeviceId,
  getJob,
  getPathInfo,
  getRuntimeInfo,
  getSystemInfo,
  isWindowMaximized,
  studioCreateInstanceTask,
  studioUpdateInstanceTask,
  listDirectory,
  listJobs,
  maximizeWindow,
  minimizeWindow,
  movePath,
  openExternal,
  pathExists,
  readBinaryFile,
  readTextFile,
  restoreWindow,
  removePath,
  saveFile,
  selectFiles,
  supportsNativeScreenshot,
  storageDelete,
  storageGetText,
  storageListKeys,
  storagePutText,
  subscribeWindowMaximized,
  submitJob,
  submitProcessJob,
  subscribeJobUpdates,
  subscribeProcessOutput,
  writeBinaryFile,
  writeTextFile,
} from './desktop/tauriBridge';
