import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readFileSync } from 'node:fs';

import { ensureTauriTargetClean } from './ensure-tauri-target-clean.mjs';
import {
  DEFAULT_NODE_VERSION,
  DEFAULT_OPENCLAW_VERSION,
} from './openclaw-release.mjs';

const modulePath = path.resolve(import.meta.dirname, 'ensure-tauri-target-clean.mjs');

assert.match(
  readFileSync(modulePath, 'utf8'),
  /if \(invokedScriptPath && invokedScriptPath === currentModulePath\) \{\s*try \{\s*runCli\(\);\s*\} catch \(error\) \{\s*console\.error\(error instanceof Error \? error\.message : String\(error\)\);\s*process\.exit\(1\);\s*\}\s*\}/s,
  'ensure-tauri-target-clean must wrap the CLI entrypoint with a top-level error handler',
);

function withTempDir(callback) {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), 'tauri-target-clean-'));

  try {
    callback(tempDir);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function writePermissionManifest(srcTauriDir, manifestName, permissionEntries) {
  const manifestDir = path.join(srcTauriDir, 'target', 'debug', 'build', 'tauri-test', 'out');
  mkdirSync(manifestDir, { recursive: true });
  writeFileSync(path.join(manifestDir, manifestName), JSON.stringify(permissionEntries), 'utf8');
}

function writeJson(filePath, value) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const permissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(permissionFile), { recursive: true });
  writeFileSync(permissionFile, 'identifier = "app:hide"', 'utf8');
  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [
    process.platform === 'win32' ? `\\\\?\\${permissionFile}` : permissionFile,
  ]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, false, 'healthy permission manifests should not trigger cleanup');
  assert.equal(existsSync(targetDir), true, 'healthy target directory must stay intact');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const missingPermissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [missingPermissionFile]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, true, 'stale permission manifests must trigger cleanup');
  assert.equal(existsSync(targetDir), false, 'stale target directory must be removed');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    nodeVersion: DEFAULT_NODE_VERSION,
    platform: 'windows',
    arch: 'x64',
    nodeRelativePath: 'runtime/node/node.exe',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw-runtime', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: '2026.3.24',
    nodeVersion: '22.16.0',
    platform: 'windows',
    arch: 'x64',
    nodeRelativePath: 'runtime/node/node.exe',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    true,
    'legacy openclaw-runtime resource directories must trigger stale target cleanup',
  );
  assert.equal(existsSync(targetDir), false, 'legacy bundled runtime target resources must be removed');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const sourceManifest = {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    nodeVersion: DEFAULT_NODE_VERSION,
    platform: 'windows',
    arch: 'x64',
    nodeRelativePath: 'runtime/node/node.exe',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  };
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), sourceManifest);
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw', 'manifest.json'), {
    ...sourceManifest,
    openclawVersion: '2026.3.24',
  });

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    true,
    'mismatched bundled openclaw target manifests must trigger stale target cleanup',
  );
  assert.equal(existsSync(targetDir), false, 'mismatched bundled runtime target manifests must be removed');
});

withTempDir((tempDir) => {
  const desktopPackageDir = path.join(tempDir, 'sdkwork-claw-desktop');
  const srcTauriDir = path.join(desktopPackageDir, 'src-tauri');
  const packageTargetDir = path.join(desktopPackageDir, '.tauri-target');
  writeJson(path.join(srcTauriDir, 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: DEFAULT_OPENCLAW_VERSION,
    nodeVersion: DEFAULT_NODE_VERSION,
    platform: 'windows',
    arch: 'x64',
    nodeRelativePath: 'runtime/node/node.exe',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });
  writeJson(
    path.join(packageTargetDir, 'dev', 'debug', 'resources', 'openclaw-runtime', 'manifest.json'),
    {
      schemaVersion: 1,
      runtimeId: 'openclaw',
      openclawVersion: '2026.3.24',
      nodeVersion: DEFAULT_NODE_VERSION,
      platform: 'windows',
      arch: 'x64',
      nodeRelativePath: 'runtime/node/node.exe',
      cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
    },
  );

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(
    result.removedTarget,
    true,
    'legacy desktop .tauri-target OpenClaw resources must trigger stale target cleanup',
  );
  assert.equal(
    existsSync(packageTargetDir),
    false,
    'legacy desktop .tauri-target resources must be removed alongside src-tauri target cleanup',
  );
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');

  mkdirSync(path.join(srcTauriDir, 'resources', 'openclaw'), { recursive: true });
  writeFileSync(path.join(srcTauriDir, 'resources', 'openclaw', '.gitkeep'), '', 'utf8');
  writeJson(path.join(targetDir, 'dev', 'debug', 'resources', 'openclaw', 'manifest.json'), {
    schemaVersion: 1,
    runtimeId: 'openclaw',
    openclawVersion: '2026.3.24',
    nodeVersion: DEFAULT_NODE_VERSION,
    platform: 'windows',
    arch: 'x64',
    nodeRelativePath: 'runtime/node/node.exe',
    cliRelativePath: 'runtime/package/node_modules/openclaw/openclaw.mjs',
  });

  const result = ensureTauriTargetClean(srcTauriDir, {
    env: {
      SDKWORK_DESKTOP_TARGET_PLATFORM: 'windows',
      SDKWORK_DESKTOP_TARGET_ARCH: 'x64',
    },
  });

  assert.equal(
    result.removedTarget,
    true,
    'stale bundled target manifests must still trigger cleanup when the source tree keeps only the openclaw placeholder',
  );
  assert.equal(
    existsSync(targetDir),
    false,
    'stale target manifests must not survive the openclaw placeholder-only source layout',
  );
});

console.log('ok - stale Tauri target cleanup only removes invalid permission caches');
