import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { ensureTauriTargetClean, resolveTauriTargetDir } from './ensure-tauri-target-clean.mjs';

function withTempDir(callback) {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), 'tauri-target-clean-'));

  try {
    callback(tempDir);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function writePermissionManifest(srcTauriDir, manifestName, permissionEntries) {
  const manifestDir = path.join(srcTauriDir, 'target', 'debug', 'build', 'tauri-test', 'out');
  mkdirSync(manifestDir, { recursive: true });
  writeFileSync(path.join(manifestDir, manifestName), JSON.stringify(permissionEntries), 'utf8');
}

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const permissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(permissionFile), { recursive: true });
  writeFileSync(permissionFile, 'identifier = "app:hide"', 'utf8');
  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [
    process.platform === 'win32' ? `\\\\?\\${permissionFile}` : permissionFile,
  ]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, false, 'healthy permission manifests should not trigger cleanup');
  assert.equal(existsSync(targetDir), true, 'healthy target directory must stay intact');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const targetDir = path.join(srcTauriDir, 'target');
  const missingPermissionFile = path.join(
    targetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  writePermissionManifest(srcTauriDir, 'tauri-core-app-permission-files', [missingPermissionFile]);

  const result = ensureTauriTargetClean(srcTauriDir);

  assert.equal(result.removedTarget, true, 'stale permission manifests must trigger cleanup');
  assert.equal(existsSync(targetDir), false, 'stale target directory must be removed');
});

withTempDir((tempDir) => {
  const srcTauriDir = path.join(tempDir, 'src-tauri');
  const cargoTargetDir = path.join(tempDir, 'custom-target');
  const permissionFile = path.join(
    cargoTargetDir,
    'debug',
    'build',
    'tauri-test',
    'out',
    'permissions',
    'app',
    'autogenerated',
    'commands',
    'app_hide.toml',
  );

  mkdirSync(path.dirname(permissionFile), { recursive: true });
  writeFileSync(permissionFile, 'identifier = "app:hide"', 'utf8');
  writeFileSync(
    path.join(cargoTargetDir, 'debug', 'build', 'tauri-test', 'out', 'tauri-core-app-permission-files'),
    JSON.stringify([process.platform === 'win32' ? `\\\\?\\${permissionFile}` : permissionFile]),
    'utf8',
  );

  const previousTargetDir = process.env.CARGO_TARGET_DIR;
  process.env.CARGO_TARGET_DIR = cargoTargetDir;
  try {
    const result = ensureTauriTargetClean(srcTauriDir);
    assert.equal(
      resolveTauriTargetDir(srcTauriDir),
      cargoTargetDir,
      'target clean helper must honor CARGO_TARGET_DIR when present',
    );
    assert.equal(result.removedTarget, false, 'healthy custom target manifests should not trigger cleanup');
    assert.equal(existsSync(cargoTargetDir), true, 'healthy custom target directory must stay intact');
  } finally {
    if (typeof previousTargetDir === 'string') {
      process.env.CARGO_TARGET_DIR = previousTargetDir;
    } else {
      delete process.env.CARGO_TARGET_DIR;
    }
  }
});

console.log('ok - stale Tauri target cleanup only removes invalid permission caches');
