export const DESKTOP_COMMANDS = {
  appInfo: 'app_info',
  appPaths: 'get_app_paths',
  appConfig: 'get_app_config',
  setAppLanguage: 'set_app_language',
  systemInfo: 'get_system_info',
  desktopKernelInfo: 'desktop_kernel_info',
  desktopStorageInfo: 'desktop_storage_info',
  studioListInstances: 'studio_list_instances',
  studioGetInstance: 'studio_get_instance',
  studioGetInstanceDetail: 'studio_get_instance_detail',
  studioCreateInstance: 'studio_create_instance',
  studioUpdateInstance: 'studio_update_instance',
  studioDeleteInstance: 'studio_delete_instance',
  studioStartInstance: 'studio_start_instance',
  studioStopInstance: 'studio_stop_instance',
  studioRestartInstance: 'studio_restart_instance',
  studioGetInstanceConfig: 'studio_get_instance_config',
  studioUpdateInstanceConfig: 'studio_update_instance_config',
  studioGetInstanceLogs: 'studio_get_instance_logs',
  studioCreateInstanceTask: 'studio_create_instance_task',
  studioUpdateInstanceTask: 'studio_update_instance_task',
  studioCloneInstanceTask: 'studio_clone_instance_task',
  studioRunInstanceTaskNow: 'studio_run_instance_task_now',
  studioListInstanceTaskExecutions: 'studio_list_instance_task_executions',
  studioUpdateInstanceTaskStatus: 'studio_update_instance_task_status',
  studioDeleteInstanceTask: 'studio_delete_instance_task',
  studioListConversations: 'studio_list_conversations',
  studioPutConversation: 'studio_put_conversation',
  studioDeleteConversation: 'studio_delete_conversation',
  storageGetText: 'storage_get_text',
  storagePutText: 'storage_put_text',
  storageDelete: 'storage_delete',
  storageListKeys: 'storage_list_keys',
  listDirectory: 'list_directory',
  pathExists: 'path_exists',
  getPathInfo: 'get_path_info',
  createDirectory: 'create_directory',
  removePath: 'remove_path',
  copyPath: 'copy_path',
  movePath: 'move_path',
  readBinaryFile: 'read_binary_file',
  writeBinaryFile: 'write_binary_file',
  readTextFile: 'read_text_file',
  writeTextFile: 'write_text_file',
  getDeviceId: 'get_device_id',
  jobSubmit: 'job_submit',
  jobSubmitProcess: 'job_submit_process',
  jobGet: 'job_get',
  jobList: 'job_list',
  jobCancel: 'job_cancel',
  listHubInstallCatalog: 'list_hub_install_catalog',
  inspectHubInstall: 'inspect_hub_install',
  runHubDependencyInstall: 'run_hub_dependency_install',
  runHubInstall: 'run_hub_install',
  runHubUninstall: 'run_hub_uninstall',
  installApiRouterClientSetup: 'install_api_router_client_setup',
  getApiRouterAdminBootstrapSession: 'get_api_router_admin_bootstrap_session',
  getApiRouterRuntimeStatus: 'get_api_router_runtime_status',
  openExternal: 'open_external',
  selectFiles: 'select_files',
  saveBlobFile: 'save_blob_file',
  fetchRemoteUrl: 'fetch_remote_url',
  captureScreenshot: 'capture_screenshot',
} as const;

export type DesktopCommandName =
  (typeof DESKTOP_COMMANDS)[keyof typeof DESKTOP_COMMANDS];

export const DESKTOP_EVENTS = {
  appReady: 'app://ready',
  hubInstallProgress: 'hub-installer:progress',
  jobUpdated: 'job://updated',
  processOutput: 'process://output',
  trayNavigate: 'tray://navigate',
} as const;

export type DesktopEventName = (typeof DESKTOP_EVENTS)[keyof typeof DESKTOP_EVENTS];
