export const DESKTOP_COMMANDS = {
  getApiRouterRuntimeStatus: 'get_api_router_runtime_status',
  getApiRouterChannels: 'get_api_router_channels',
  getApiRouterGroups: 'get_api_router_groups',
  getApiRouterProxyProviders: 'get_api_router_proxy_providers',
  createApiRouterProxyProvider: 'create_api_router_proxy_provider',
  updateApiRouterProxyProviderGroup: 'update_api_router_proxy_provider_group',
  updateApiRouterProxyProviderStatus: 'update_api_router_proxy_provider_status',
  updateApiRouterProxyProvider: 'update_api_router_proxy_provider',
  deleteApiRouterProxyProvider: 'delete_api_router_proxy_provider',
  getApiRouterUsageRecordApiKeys: 'get_api_router_usage_record_api_keys',
  getApiRouterUsageRecordSummary: 'get_api_router_usage_record_summary',
  getApiRouterUsageRecords: 'get_api_router_usage_records',
  getApiRouterUnifiedApiKeys: 'get_api_router_unified_api_keys',
  createApiRouterUnifiedApiKey: 'create_api_router_unified_api_key',
  updateApiRouterUnifiedApiKeyGroup: 'update_api_router_unified_api_key_group',
  updateApiRouterUnifiedApiKeyStatus: 'update_api_router_unified_api_key_status',
  assignApiRouterUnifiedApiKeyModelMapping: 'assign_api_router_unified_api_key_model_mapping',
  updateApiRouterUnifiedApiKey: 'update_api_router_unified_api_key',
  deleteApiRouterUnifiedApiKey: 'delete_api_router_unified_api_key',
  getApiRouterModelCatalog: 'get_api_router_model_catalog',
  getApiRouterModelMappings: 'get_api_router_model_mappings',
  createApiRouterModelMapping: 'create_api_router_model_mapping',
  updateApiRouterModelMapping: 'update_api_router_model_mapping',
  updateApiRouterModelMappingStatus: 'update_api_router_model_mapping_status',
  deleteApiRouterModelMapping: 'delete_api_router_model_mapping',
  appInfo: 'app_info',
  appPaths: 'get_app_paths',
  appConfig: 'get_app_config',
  setAppLanguage: 'set_app_language',
  systemInfo: 'get_system_info',
  desktopComponentCatalog: 'desktop_component_catalog',
  desktopComponentControl: 'desktop_component_control',
  desktopKernelInfo: 'desktop_kernel_info',
  desktopStorageInfo: 'desktop_storage_info',
  studioListInstances: 'studio_list_instances',
  studioGetInstance: 'studio_get_instance',
  studioGetInstanceDetail: 'studio_get_instance_detail',
  studioCreateInstance: 'studio_create_instance',
  studioUpdateInstance: 'studio_update_instance',
  studioDeleteInstance: 'studio_delete_instance',
  studioStartInstance: 'studio_start_instance',
  studioStopInstance: 'studio_stop_instance',
  studioRestartInstance: 'studio_restart_instance',
  studioGetInstanceConfig: 'studio_get_instance_config',
  studioUpdateInstanceConfig: 'studio_update_instance_config',
  studioGetInstanceLogs: 'studio_get_instance_logs',
  studioCreateInstanceTask: 'studio_create_instance_task',
  studioUpdateInstanceTask: 'studio_update_instance_task',
  studioUpdateInstanceFileContent: 'studio_update_instance_file_content',
  studioUpdateInstanceLlmProviderConfig: 'studio_update_instance_llm_provider_config',
  studioCloneInstanceTask: 'studio_clone_instance_task',
  studioRunInstanceTaskNow: 'studio_run_instance_task_now',
  studioListInstanceTaskExecutions: 'studio_list_instance_task_executions',
  studioUpdateInstanceTaskStatus: 'studio_update_instance_task_status',
  studioDeleteInstanceTask: 'studio_delete_instance_task',
  studioListConversations: 'studio_list_conversations',
  studioPutConversation: 'studio_put_conversation',
  studioDeleteConversation: 'studio_delete_conversation',
  storageGetText: 'storage_get_text',
  storagePutText: 'storage_put_text',
  storageDelete: 'storage_delete',
  storageListKeys: 'storage_list_keys',
  listDirectory: 'list_directory',
  pathExists: 'path_exists',
  getPathInfo: 'get_path_info',
  createDirectory: 'create_directory',
  removePath: 'remove_path',
  copyPath: 'copy_path',
  movePath: 'move_path',
  readBinaryFile: 'read_binary_file',
  writeBinaryFile: 'write_binary_file',
  readTextFile: 'read_text_file',
  writeTextFile: 'write_text_file',
  getDeviceId: 'get_device_id',
  jobSubmit: 'job_submit',
  jobSubmitProcess: 'job_submit_process',
  jobGet: 'job_get',
  jobList: 'job_list',
  jobCancel: 'job_cancel',
  listHubInstallCatalog: 'list_hub_install_catalog',
  inspectHubInstall: 'inspect_hub_install',
  runHubDependencyInstall: 'run_hub_dependency_install',
  runHubInstall: 'run_hub_install',
  runHubUninstall: 'run_hub_uninstall',
  installApiRouterClientSetup: 'install_api_router_client_setup',
  getApiRouterAdminBootstrapSession: 'get_api_router_admin_bootstrap_session',
  openExternal: 'open_external',
  selectFiles: 'select_files',
  saveBlobFile: 'save_blob_file',
  fetchRemoteUrl: 'fetch_remote_url',
  captureScreenshot: 'capture_screenshot',
} as const;

export type DesktopCommandName =
  (typeof DESKTOP_COMMANDS)[keyof typeof DESKTOP_COMMANDS];

export const DESKTOP_EVENTS = {
  appReady: 'app://ready',
  hubInstallProgress: 'hub-installer:progress',
  jobUpdated: 'job://updated',
  processOutput: 'process://output',
  trayNavigate: 'tray://navigate',
} as const;

export type DesktopEventName = (typeof DESKTOP_EVENTS)[keyof typeof DESKTOP_EVENTS];
