apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "claw-studio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "claw-studio.name" . }}
    helm.sh/chart: {{ include "claw-studio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "claw-studio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "claw-studio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: claw-studio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "claw-studio.fullname" . }}-config
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
{{- if eq .Values.targetArchitecture "arm64" }}
        kubernetes.io/arch: arm64
{{- else }}
        kubernetes.io/arch: amd64
{{- end }}
{{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
{{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
