{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "claw-studio.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "claw-studio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
{{- end }}
